s3:
  uploadbucket: document-service-uploaddocs-963166549396-prod
spring:
  flyway:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: Test1234
    locations: classpath:db/callback, classpath:db/migration/postgres
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: password
logging:
  level:
    com.edu.remotecollab.service: ERROR
    org.spring.security.web: WARN
